spring:
  application:
    name: eureka-server

server:
  port: @eureka.server.port@

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://@eureka.server.host@:@eureka.server.port@/eureka/
  instance:
    prefer-ip-address: true
