server:
  port: 8769

spring:
  application:
    name: ms-gateway
eureka:
  client:
    service-url:
      defaultZone: http://@eureka.server.host@:@eureka.server.port@/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    morning-os-web: /morning-os-web/**
    morning-cms-web: /morning-cms-web/**

logging:
  level:
    com.netflix: DEBUG
    org.lanwei: DEBUG
##  file: /opt/deploy/logs/ms-gateway.log

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000


