server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/LanWei-HNU/config-example.git
          search-paths: morning


eureka:
  client:
    service-url:
      defaultZone: http://@eureka.server.host@:@eureka.server.port@/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.netflix: DEBUG
    org.lanwei: DEBUG
##  file: /opt/deploy/logs/config-server.log



